### ISSUE TITLE
Transforming into a bird/bat while holding a cloaking device makes them permanently cloaked

### ISSUE THREAD

**Issue by ToFurkie** [Alf21/ttt2-role_vamp#2]
Did this multiple times while testing some stuff with the shops. If you actively have a cloaking device held in your hand and are cloaked, when you transform, you will remain invisible in your player model state. There is also no way to return to being uncloaked, even if you switch off of it

**Comment by Histalek** [comment]
We are aware of the problem, but it lies more with the specific cloaking device addons and how they handle their removal from the player inventory.

Therefore i will close this issue. Thank you for bringing this to our attention nonetheless :)

Additionally for anyone looking for a working addon: [this cloaking device](https://steamcommunity.com/sharedfiles/filedetails/?id=1802717950) should function properly with the vampire as it is a passive item instead of a hold weapon.
